// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdttbsntcjujwygavhbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkdHRic250Y2p1and5Z2F2aGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MjE0ODMsImV4cCI6MjA1NzA5NzQ4M30.9R3FTDBfoAcxL4MIn1Ufjxh_e2LMhnKgLanHZZW69fA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);